### ISSUE TITLE
elasticsearch with authentication

### ISSUE THREAD

**Issue by selyod-ka** [zammad/zammad-documentation#182]
hi,
you mention two possibilities in order to add authentication to ES. https://docs.zammad.org/en/latest/install/elasticsearch.html#optional-settings

i'd like to hint you at https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md 
i've set it up according to that docs and configured
```

cat /etc/elasticsearch/readonlyrest.yml 
readonlyrest:
  access_control_rules:
  - name: Accept requests for zammad 
    groups: ["zammad"]
    indices: ["zammad_index*"]
    
  users:
  - username: zammad
    auth_key: zammad:*************
    groups: ["zammad"]

```

and changed the 'Index namespacing'
`zammad run rails r "Setting.set('es_index', 'zammad_index')"`

it works now with authentication, without X-Pack.
