### ISSUE TITLE
The documentation does not state information on permissions needed for the Elasticsearch user used to connect to Elasticsearch server

### ISSUE THREAD

**Issue by oussjarrousse** [zammad/zammad-documentation#247]
While attempting to connect my zammad installation with an elasticsearch that I am hosting on another device. I created a special Elsaticsearch user for Zammad. I did not want to give too much permissions to the zammad ES user. However I did not find in the documentation the list of permissions required for a successful integration of EL and Zammad. https://docs.zammad.org/en/latest/install/elasticsearch.html

Eventually I ended up using the following solution:

Define a new EL role with the following permissions:

- Cluster privileges: monitor, manage_ingest_pipelines
- Index privileges:
  - indices: Zammad_*
  - privileges: create_index, create_doc, create, read
  
I think this info should be added to the documentation exactly here:
https://docs.zammad.org/en/latest/install/elasticsearch.html

**Comment by zerwes** [comment]
for me it is only working with the `manage` priv included.
```yml
zammad:
  cluster: [ "monitor", "manage_ingest_pipelines" ]
  indices:
    - names: [ 'Zammad_*', 'zammad_*' ]
      privileges: [ 'create_index', 'create_doc', 'create', 'read', 'manage' ]
  run_as: ["*"]
```
with
```
elasticsearch  8.11.3
zammad         6.2.0-1704392455.bba4f84a.bookworm 
```

But I fully agree that the required information should be provided in the documentation!
